let solid = () => {
  <div>
    <Solid.AcademicCapIcon />
    <Solid.AdjustmentsIcon />
    <Solid.AnnotationIcon />
    <Solid.ArchiveIcon />
    <Solid.ArrowCircleDownIcon />
    <Solid.ArrowCircleLeftIcon />
    <Solid.ArrowCircleRightIcon />
    <Solid.ArrowCircleUpIcon />
    <Solid.ArrowDownIcon />
    <Solid.ArrowLeftIcon />
    <Solid.ArrowNarrowDownIcon />
    <Solid.ArrowNarrowLeftIcon />
    <Solid.ArrowNarrowRightIcon />
    <Solid.ArrowNarrowUpIcon />
    <Solid.ArrowRightIcon />
    <Solid.ArrowSmDownIcon />
    <Solid.ArrowSmLeftIcon />
    <Solid.ArrowSmRightIcon />
    <Solid.ArrowSmUpIcon />
    <Solid.ArrowUpIcon />
    <Solid.ArrowsExpandIcon />
    <Solid.AtSymbolIcon />
    <Solid.BackspaceIcon />
    <Solid.BadgeCheckIcon />
    <Solid.BanIcon />
    <Solid.BeakerIcon />
    <Solid.BellIcon />
    <Solid.BookOpenIcon />
    <Solid.BookmarkAltIcon />
    <Solid.BookmarkIcon />
    <Solid.BriefcaseIcon />
    <Solid.CakeIcon />
    <Solid.CalculatorIcon />
    <Solid.CalendarIcon />
    <Solid.CameraIcon />
    <Solid.CashIcon />
    <Solid.ChartBarIcon />
    <Solid.ChartPieIcon />
    <Solid.ChartSquareBarIcon />
    <Solid.ChatAlt2Icon />
    <Solid.ChatAltIcon />
    <Solid.ChatIcon />
    <Solid.CheckCircleIcon />
    <Solid.CheckIcon />
    <Solid.ChevronDoubleDownIcon />
    <Solid.ChevronDoubleLeftIcon />
    <Solid.ChevronDoubleRightIcon />
    <Solid.ChevronDoubleUpIcon />
    <Solid.ChevronDownIcon />
    <Solid.ChevronLeftIcon />
    <Solid.ChevronRightIcon />
    <Solid.ChevronUpIcon />
    <Solid.ChipIcon />
    <Solid.ClipboardCheckIcon />
    <Solid.ClipboardCopyIcon />
    <Solid.ClipboardIcon />
    <Solid.ClipboardListIcon />
    <Solid.ClockIcon />
    <Solid.CloudDownloadIcon />
    <Solid.CloudIcon />
    <Solid.CloudUploadIcon />
    <Solid.CodeIcon />
    <Solid.CogIcon />
    <Solid.CollectionIcon />
    <Solid.ColorSwatchIcon />
    <Solid.CreditCardIcon />
    <Solid.CubeIcon />
    <Solid.CubeTransparentIcon />
    <Solid.CurrencyBangladeshiIcon />
    <Solid.CurrencyDollarIcon />
    <Solid.CurrencyEuroIcon />
    <Solid.CurrencyPoundIcon />
    <Solid.CurrencyRupeeIcon />
    <Solid.CurrencyYenIcon />
    <Solid.CursorClickIcon />
    <Solid.DatabaseIcon />
    <Solid.DesktopComputerIcon />
    <Solid.DeviceMobileIcon />
    <Solid.DeviceTabletIcon />
    <Solid.DocumentAddIcon />
    <Solid.DocumentDownloadIcon />
    <Solid.DocumentDuplicateIcon />
    <Solid.DocumentIcon />
    <Solid.DocumentRemoveIcon />
    <Solid.DocumentReportIcon />
    <Solid.DocumentSearchIcon />
    <Solid.DocumentTextIcon />
    <Solid.DotsCircleHorizontalIcon />
    <Solid.DotsHorizontalIcon />
    <Solid.DotsVerticalIcon />
    <Solid.DownloadIcon />
    <Solid.DuplicateIcon />
    <Solid.EmojiHappyIcon />
    <Solid.EmojiSadIcon />
    <Solid.ExclamationCircleIcon />
    <Solid.ExclamationIcon />
    <Solid.ExternalLinkIcon />
    <Solid.EyeIcon />
    <Solid.EyeOffIcon />
    <Solid.FastForwardIcon />
    <Solid.FilmIcon />
    <Solid.FilterIcon />
    <Solid.FingerPrintIcon />
    <Solid.FireIcon />
    <Solid.FlagIcon />
    <Solid.FolderAddIcon />
    <Solid.FolderDownloadIcon />
    <Solid.FolderIcon />
    <Solid.FolderOpenIcon />
    <Solid.FolderRemoveIcon />
    <Solid.GiftIcon />
    <Solid.GlobeAltIcon />
    <Solid.GlobeIcon />
    <Solid.HandIcon />
    <Solid.HashtagIcon />
    <Solid.HeartIcon />
    <Solid.HomeIcon />
    <Solid.IdentificationIcon />
    <Solid.InboxIcon />
    <Solid.InboxInIcon />
    <Solid.InformationCircleIcon />
    <Solid.KeyIcon />
    <Solid.LibraryIcon />
    <Solid.LightBulbIcon />
    <Solid.LightningBoltIcon />
    <Solid.LinkIcon />
    <Solid.LocationMarkerIcon />
    <Solid.LockClosedIcon />
    <Solid.LockOpenIcon />
    <Solid.LoginIcon />
    <Solid.LogoutIcon />
    <Solid.MailIcon />
    <Solid.MailOpenIcon />
    <Solid.MapIcon />
    <Solid.MenuAlt1Icon />
    <Solid.MenuAlt2Icon />
    <Solid.MenuAlt3Icon />
    <Solid.MenuAlt4Icon />
    <Solid.MenuIcon />
    <Solid.MicrophoneIcon />
    <Solid.MinusCircleIcon />
    <Solid.MinusIcon />
    <Solid.MinusSmIcon />
    <Solid.MoonIcon />
    <Solid.MusicNoteIcon />
    <Solid.NewspaperIcon />
    <Solid.OfficeBuildingIcon />
    <Solid.PaperAirplaneIcon />
    <Solid.PaperClipIcon />
    <Solid.PauseIcon />
    <Solid.PencilAltIcon />
    <Solid.PencilIcon />
    <Solid.PhoneIcon />
    <Solid.PhoneIncomingIcon />
    <Solid.PhoneMissedCallIcon />
    <Solid.PhoneOutgoingIcon />
    <Solid.PhotographIcon />
    <Solid.PlayIcon />
    <Solid.PlusCircleIcon />
    <Solid.PlusIcon />
    <Solid.PlusSmIcon />
    <Solid.PresentationChartBarIcon />
    <Solid.PresentationChartLineIcon />
    <Solid.PrinterIcon />
    <Solid.PuzzleIcon />
    <Solid.QrcodeIcon />
    <Solid.QuestionMarkCircleIcon />
    <Solid.ReceiptRefundIcon />
    <Solid.ReceiptTaxIcon />
    <Solid.RefreshIcon />
    <Solid.ReplyIcon />
    <Solid.RewindIcon />
    <Solid.RssIcon />
    <Solid.SaveAsIcon />
    <Solid.SaveIcon />
    <Solid.ScaleIcon />
    <Solid.ScissorsIcon />
    <Solid.SearchCircleIcon />
    <Solid.SearchIcon />
    <Solid.SelectorIcon />
    <Solid.ServerIcon />
    <Solid.ShareIcon />
    <Solid.ShieldCheckIcon />
    <Solid.ShieldExclamationIcon />
    <Solid.ShoppingBagIcon />
    <Solid.ShoppingCartIcon />
    <Solid.SortAscendingIcon />
    <Solid.SortDescendingIcon />
    <Solid.SparklesIcon />
    <Solid.SpeakerphoneIcon />
    <Solid.StarIcon />
    <Solid.StatusOfflineIcon />
    <Solid.StatusOnlineIcon />
    <Solid.StopIcon />
    <Solid.SunIcon />
    <Solid.SupportIcon />
    <Solid.SwitchHorizontalIcon />
    <Solid.SwitchVerticalIcon />
    <Solid.TableIcon />
    <Solid.TagIcon />
    <Solid.TemplateIcon />
    <Solid.TerminalIcon />
    <Solid.ThumbDownIcon />
    <Solid.ThumbUpIcon />
    <Solid.TicketIcon />
    <Solid.TranslateIcon />
    <Solid.TrashIcon />
    <Solid.TrendingDownIcon />
    <Solid.TrendingUpIcon />
    <Solid.TruckIcon />
    <Solid.UploadIcon />
    <Solid.UserAddIcon />
    <Solid.UserCircleIcon />
    <Solid.UserGroupIcon />
    <Solid.UserIcon />
    <Solid.UserRemoveIcon />
    <Solid.UsersIcon />
    <Solid.VariableIcon />
    <Solid.VideoCameraIcon />
    <Solid.ViewBoardsIcon />
    <Solid.ViewGridAddIcon />
    <Solid.ViewGridIcon />
    <Solid.ViewListIcon />
    <Solid.VolumeOffIcon />
    <Solid.VolumeUpIcon />
    <Solid.WifiIcon />
    <Solid.XCircleIcon />
    <Solid.XIcon />
    <Solid.ZoomInIcon />
    <Solid.ZoomOutIcon />
  </div>
}

let outline = () => {
  <div>
    <Outline.AcademicCapIcon />
    <Outline.AdjustmentsIcon />
    <Outline.AnnotationIcon />
    <Outline.ArchiveIcon />
    <Outline.ArrowCircleDownIcon />
    <Outline.ArrowCircleLeftIcon />
    <Outline.ArrowCircleRightIcon />
    <Outline.ArrowCircleUpIcon />
    <Outline.ArrowDownIcon />
    <Outline.ArrowLeftIcon />
    <Outline.ArrowNarrowDownIcon />
    <Outline.ArrowNarrowLeftIcon />
    <Outline.ArrowNarrowRightIcon />
    <Outline.ArrowNarrowUpIcon />
    <Outline.ArrowRightIcon />
    <Outline.ArrowSmDownIcon />
    <Outline.ArrowSmLeftIcon />
    <Outline.ArrowSmRightIcon />
    <Outline.ArrowSmUpIcon />
    <Outline.ArrowUpIcon />
    <Outline.ArrowsExpandIcon />
    <Outline.AtSymbolIcon />
    <Outline.BackspaceIcon />
    <Outline.BadgeCheckIcon />
    <Outline.BanIcon />
    <Outline.BeakerIcon />
    <Outline.BellIcon />
    <Outline.BookOpenIcon />
    <Outline.BookmarkAltIcon />
    <Outline.BookmarkIcon />
    <Outline.BriefcaseIcon />
    <Outline.CakeIcon />
    <Outline.CalculatorIcon />
    <Outline.CalendarIcon />
    <Outline.CameraIcon />
    <Outline.CashIcon />
    <Outline.ChartBarIcon />
    <Outline.ChartPieIcon />
    <Outline.ChartSquareBarIcon />
    <Outline.ChatAlt2Icon />
    <Outline.ChatAltIcon />
    <Outline.ChatIcon />
    <Outline.CheckCircleIcon />
    <Outline.CheckIcon />
    <Outline.ChevronDoubleDownIcon />
    <Outline.ChevronDoubleLeftIcon />
    <Outline.ChevronDoubleRightIcon />
    <Outline.ChevronDoubleUpIcon />
    <Outline.ChevronDownIcon />
    <Outline.ChevronLeftIcon />
    <Outline.ChevronRightIcon />
    <Outline.ChevronUpIcon />
    <Outline.ChipIcon />
    <Outline.ClipboardCheckIcon />
    <Outline.ClipboardCopyIcon />
    <Outline.ClipboardIcon />
    <Outline.ClipboardListIcon />
    <Outline.ClockIcon />
    <Outline.CloudDownloadIcon />
    <Outline.CloudIcon />
    <Outline.CloudUploadIcon />
    <Outline.CodeIcon />
    <Outline.CogIcon />
    <Outline.CollectionIcon />
    <Outline.ColorSwatchIcon />
    <Outline.CreditCardIcon />
    <Outline.CubeIcon />
    <Outline.CubeTransparentIcon />
    <Outline.CurrencyBangladeshiIcon />
    <Outline.CurrencyDollarIcon />
    <Outline.CurrencyEuroIcon />
    <Outline.CurrencyPoundIcon />
    <Outline.CurrencyRupeeIcon />
    <Outline.CurrencyYenIcon />
    <Outline.CursorClickIcon />
    <Outline.DatabaseIcon />
    <Outline.DesktopComputerIcon />
    <Outline.DeviceMobileIcon />
    <Outline.DeviceTabletIcon />
    <Outline.DocumentAddIcon />
    <Outline.DocumentDownloadIcon />
    <Outline.DocumentDuplicateIcon />
    <Outline.DocumentIcon />
    <Outline.DocumentRemoveIcon />
    <Outline.DocumentReportIcon />
    <Outline.DocumentSearchIcon />
    <Outline.DocumentTextIcon />
    <Outline.DotsCircleHorizontalIcon />
    <Outline.DotsHorizontalIcon />
    <Outline.DotsVerticalIcon />
    <Outline.DownloadIcon />
    <Outline.DuplicateIcon />
    <Outline.EmojiHappyIcon />
    <Outline.EmojiSadIcon />
    <Outline.ExclamationCircleIcon />
    <Outline.ExclamationIcon />
    <Outline.ExternalLinkIcon />
    <Outline.EyeIcon />
    <Outline.EyeOffIcon />
    <Outline.FastForwardIcon />
    <Outline.FilmIcon />
    <Outline.FilterIcon />
    <Outline.FingerPrintIcon />
    <Outline.FireIcon />
    <Outline.FlagIcon />
    <Outline.FolderAddIcon />
    <Outline.FolderDownloadIcon />
    <Outline.FolderIcon />
    <Outline.FolderOpenIcon />
    <Outline.FolderRemoveIcon />
    <Outline.GiftIcon />
    <Outline.GlobeAltIcon />
    <Outline.GlobeIcon />
    <Outline.HandIcon />
    <Outline.HashtagIcon />
    <Outline.HeartIcon />
    <Outline.HomeIcon />
    <Outline.IdentificationIcon />
    <Outline.InboxIcon />
    <Outline.InboxInIcon />
    <Outline.InformationCircleIcon />
    <Outline.KeyIcon />
    <Outline.LibraryIcon />
    <Outline.LightBulbIcon />
    <Outline.LightningBoltIcon />
    <Outline.LinkIcon />
    <Outline.LocationMarkerIcon />
    <Outline.LockClosedIcon />
    <Outline.LockOpenIcon />
    <Outline.LoginIcon />
    <Outline.LogoutIcon />
    <Outline.MailIcon />
    <Outline.MailOpenIcon />
    <Outline.MapIcon />
    <Outline.MenuAlt1Icon />
    <Outline.MenuAlt2Icon />
    <Outline.MenuAlt3Icon />
    <Outline.MenuAlt4Icon />
    <Outline.MenuIcon />
    <Outline.MicrophoneIcon />
    <Outline.MinusCircleIcon />
    <Outline.MinusIcon />
    <Outline.MinusSmIcon />
    <Outline.MoonIcon />
    <Outline.MusicNoteIcon />
    <Outline.NewspaperIcon />
    <Outline.OfficeBuildingIcon />
    <Outline.PaperAirplaneIcon />
    <Outline.PaperClipIcon />
    <Outline.PauseIcon />
    <Outline.PencilAltIcon />
    <Outline.PencilIcon />
    <Outline.PhoneIcon />
    <Outline.PhoneIncomingIcon />
    <Outline.PhoneMissedCallIcon />
    <Outline.PhoneOutgoingIcon />
    <Outline.PhotographIcon />
    <Outline.PlayIcon />
    <Outline.PlusCircleIcon />
    <Outline.PlusIcon />
    <Outline.PlusSmIcon />
    <Outline.PresentationChartBarIcon />
    <Outline.PresentationChartLineIcon />
    <Outline.PrinterIcon />
    <Outline.PuzzleIcon />
    <Outline.QrcodeIcon />
    <Outline.QuestionMarkCircleIcon />
    <Outline.ReceiptRefundIcon />
    <Outline.ReceiptTaxIcon />
    <Outline.RefreshIcon />
    <Outline.ReplyIcon />
    <Outline.RewindIcon />
    <Outline.RssIcon />
    <Outline.SaveAsIcon />
    <Outline.SaveIcon />
    <Outline.ScaleIcon />
    <Outline.ScissorsIcon />
    <Outline.SearchCircleIcon />
    <Outline.SearchIcon />
    <Outline.SelectorIcon />
    <Outline.ServerIcon />
    <Outline.ShareIcon />
    <Outline.ShieldCheckIcon />
    <Outline.ShieldExclamationIcon />
    <Outline.ShoppingBagIcon />
    <Outline.ShoppingCartIcon />
    <Outline.SortAscendingIcon />
    <Outline.SortDescendingIcon />
    <Outline.SparklesIcon />
    <Outline.SpeakerphoneIcon />
    <Outline.StarIcon />
    <Outline.StatusOfflineIcon />
    <Outline.StatusOnlineIcon />
    <Outline.StopIcon />
    <Outline.SunIcon />
    <Outline.SupportIcon />
    <Outline.SwitchHorizontalIcon />
    <Outline.SwitchVerticalIcon />
    <Outline.TableIcon />
    <Outline.TagIcon />
    <Outline.TemplateIcon />
    <Outline.TerminalIcon />
    <Outline.ThumbDownIcon />
    <Outline.ThumbUpIcon />
    <Outline.TicketIcon />
    <Outline.TranslateIcon />
    <Outline.TrashIcon />
    <Outline.TrendingDownIcon />
    <Outline.TrendingUpIcon />
    <Outline.TruckIcon />
    <Outline.UploadIcon />
    <Outline.UserAddIcon />
    <Outline.UserCircleIcon />
    <Outline.UserGroupIcon />
    <Outline.UserIcon />
    <Outline.UserRemoveIcon />
    <Outline.UsersIcon />
    <Outline.VariableIcon />
    <Outline.VideoCameraIcon />
    <Outline.ViewBoardsIcon />
    <Outline.ViewGridAddIcon />
    <Outline.ViewGridIcon />
    <Outline.ViewListIcon />
    <Outline.VolumeOffIcon />
    <Outline.VolumeUpIcon />
    <Outline.WifiIcon />
    <Outline.XCircleIcon />
    <Outline.XIcon />
    <Outline.ZoomInIcon />
    <Outline.ZoomOutIcon />
  </div>
}
